[package]
name = "Lumina"
version = "0.1.0"
authors = ["Michael Riley <riley117@pnw.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.6"
prost = "0.6.1"

[build-dependencies]
prost-build = "0.6.1"